import { Spell } from '../types/Character';

export const ALL_SPELLS: Omit<Spell, 'id' | 'prepared'>[] = [
    // Cantrips (Level 0)
    {
        name: 'Acid Splash',
        level: 0,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S',
        description: 'You hurl a bubble of acid. Choose one creature within range, or two creatures within 5 feet of each other.',
        element: 'acid',
        diceRoll: '1d6',
        damageType: 'acid',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Blade Ward',
        level: 0,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Chill Touch',
        level: 0,
        school: 'Necromancy',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You create a ghostly, skeletal hand that attacks a creature.',
        element: 'necrotic',
        diceRoll: '1d8',
        damageType: 'necrotic',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Dancing Lights',
        level: 0,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'You create up to four torch-sized lights within range.',
        element: 'radiant',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Fire Bolt',
        level: 0,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You hurl a mote of fire at a creature or object within range.',
        element: 'fire',
        diceRoll: '1d10',
        damageType: 'fire',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Guidance',
        level: 0,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice.',
        requiresConcentration: true,
        classes: ['Cleric', 'Druid', 'Artificer'],
    },
    {
        name: 'Light',
        level: 0,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, M',
        description: 'You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light.',
        element: 'radiant',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Mage Hand',
        level: 0,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'A spectral, floating hand appears at a point you choose within range.',
        element: 'force',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Mending',
        level: 0,
        school: 'Transmutation',
        castingTime: '1 minute',
        range: 'Touch',
        components: 'V, S, M',
        description: 'This spell repairs a single break or tear in an object you touch.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Message',
        level: 0,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'You point your finger toward a creature within range and whisper a message.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Minor Illusion',
        level: 0,
        school: 'Illusion',
        castingTime: '1 action',
        range: '30 ft',
        components: 'S, M',
        description: 'You create a sound or an image of an object within range that lasts for the duration.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Poison Spray',
        level: 0,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '10 ft',
        components: 'V, S',
        description: 'You project a puff of noxious gas.',
        element: 'poison',
        diceRoll: '1d12',
        damageType: 'poison',
        requiresConcentration: false,
        classes: ['Druid', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Prestidigitation',
        level: 0,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '10 ft',
        components: 'V, S',
        description: 'This spell is a minor magical trick that novice spellcasters use for practice.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Ray of Frost',
        level: 0,
        school: 'Evocation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S',
        description: 'A frigid beam of blue-white light streaks toward a creature within range.',
        element: 'cold',
        diceRoll: '1d8',
        damageType: 'cold',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Shillelagh',
        level: 0,
        school: 'Transmutation',
        castingTime: '1 bonus action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'The wood of a club or quarterstaff you are holding is imbued with nature\'s power.',
        requiresConcentration: false,
        classes: ['Druid'],
    },
    {
        name: 'Spare the Dying',
        level: 0,
        school: 'Necromancy',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'You touch a living creature that has 0 hit points. The creature becomes stable.',
        element: 'healing',
        requiresConcentration: false,
        classes: ['Cleric', 'Artificer'],
    },
    {
        name: 'Thaumaturgy',
        level: 0,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V',
        description: 'You manifest a minor wonder, a sign of supernatural power, within range.',
        requiresConcentration: false,
        classes: ['Cleric'],
    },
    {
        name: 'True Strike',
        level: 0,
        school: 'Divination',
        castingTime: '1 action',
        range: '30 ft',
        components: 'S',
        description: 'You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target\'s defenses.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },

    // Level 1
    {
        name: 'Alarm',
        level: 1,
        school: 'Abjuration',
        castingTime: '1 minute',
        range: '30 ft',
        components: 'V, S, M',
        description: 'You set an alarm against unwanted intrusion.',
        requiresConcentration: false,
        classes: ['Ranger', 'Wizard', 'Artificer'],
    },
    {
        name: 'Animal Friendship',
        level: 1,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'You attempt to charm a beast that you can see within range.',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Ranger'],
    },
    {
        name: 'Bane',
        level: 1,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'Up to three creatures must make Charisma saving throws. On a failure, they subtract 1d4 from attack rolls and saving throws.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Warlock'],
    },
    {
        name: 'Bless',
        level: 1,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'You bless up to three creatures. They add 1d4 to attack rolls and saving throws.',
        requiresConcentration: true,
        classes: ['Cleric', 'Paladin'],
    },
    {
        name: 'Burning Hands',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Self (15-foot cone)',
        components: 'V, S',
        description: 'A thin sheet of flames shoots forth from your outstretched fingertips.',
        element: 'fire',
        diceRoll: '3d6',
        damageType: 'fire',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Charm Person',
        level: 1,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'You attempt to charm a humanoid you can see within range.',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Chromatic Orb',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'You hurl a sphere of energy. Choose acid, cold, fire, lightning, poison, or thunder.',
        element: 'force',
        diceRoll: '3d8',
        damageType: 'varies',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Cure Wounds',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'A creature you touch regains hit points equal to 1d8 + your spellcasting ability modifier.',
        element: 'healing',
        diceRoll: '1d8',
        damageType: 'healing',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Artificer'],
    },
    {
        name: 'Detect Magic',
        level: 1,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'For the duration, you sense the presence of magic within 30 feet of you.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Disguise Self',
        level: 1,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'You make yourself—including your clothing, armor, weapons, and other belongings—look different.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Expeditious Retreat',
        level: 1,
        school: 'Transmutation',
        castingTime: '1 bonus action',
        range: 'Self',
        components: 'V, S',
        description: 'You can take the Dash action as a bonus action on each of your turns until the spell ends.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Faerie Fire',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V',
        description: 'Each object in a 20-foot cube is outlined in light. Creatures in the area are also outlined if they fail a Dexterity saving throw.',
        element: 'radiant',
        requiresConcentration: true,
        classes: ['Bard', 'Druid'],
    },
    {
        name: 'False Life',
        level: 1,
        school: 'Necromancy',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S, M',
        description: 'You gain 1d4+4 temporary hit points for the duration.',
        element: 'necrotic',
        diceRoll: '1d4+4',
        damageType: 'healing',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Feather Fall',
        level: 1,
        school: 'Transmutation',
        castingTime: '1 reaction',
        range: '60 ft',
        components: 'V, M',
        description: 'Choose up to five falling creatures within range. Their rate of descent slows to 60 feet per round.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Find Familiar',
        level: 1,
        school: 'Conjuration',
        castingTime: '1 hour',
        range: '10 ft',
        components: 'V, S, M',
        description: 'You gain the service of a familiar, a spirit that takes an animal form you choose.',
        requiresConcentration: false,
        classes: ['Wizard'],
    },
    {
        name: 'Fog Cloud',
        level: 1,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You create a 20-foot-radius sphere of fog. The sphere spreads around corners, and its area is heavily obscured.',
        requiresConcentration: true,
        classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Grease',
        level: 1,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'Slick grease covers the ground in a 10-foot square and turns it into difficult terrain.',
        requiresConcentration: false,
        classes: ['Wizard', 'Artificer'],
    },
    {
        name: 'Guiding Bolt',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'A flash of light streaks toward a creature. On a hit, the target takes 4d6 radiant damage, and the next attack roll against it has advantage.',
        element: 'radiant',
        diceRoll: '4d6',
        damageType: 'radiant',
        requiresConcentration: false,
        classes: ['Cleric'],
    },
    {
        name: 'Healing Word',
        level: 1,
        school: 'Evocation',
        castingTime: '1 bonus action',
        range: '60 ft',
        components: 'V',
        description: 'A creature of your choice regains hit points equal to 1d4 + your spellcasting ability modifier.',
        element: 'healing',
        diceRoll: '1d4',
        damageType: 'healing',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid'],
    },
    {
        name: 'Hellish Rebuke',
        level: 1,
        school: 'Evocation',
        castingTime: '1 reaction',
        range: '60 ft',
        components: 'V, S',
        description: 'The creature that damaged you is momentarily surrounded by hellish flames. It takes 2d10 fire damage on a failed save.',
        element: 'fire',
        diceRoll: '2d10',
        damageType: 'fire',
        requiresConcentration: false,
        classes: ['Warlock'],
    },
    {
        name: 'Identify',
        level: 1,
        school: 'Divination',
        castingTime: '1 minute',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You choose one object that you must touch throughout the casting. If it is a magic item, you learn its properties.',
        requiresConcentration: false,
        classes: ['Bard', 'Wizard', 'Artificer'],
    },
    {
        name: 'Illusory Script',
        level: 1,
        school: 'Illusion',
        castingTime: '1 minute',
        range: 'Touch',
        components: 'S, M',
        description: 'You write on parchment and imbue it with a potent illusion that lasts for the duration.',
        requiresConcentration: false,
        classes: ['Bard', 'Warlock', 'Wizard'],
    },
    {
        name: 'Inflict Wounds',
        level: 1,
        school: 'Necromancy',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'Make a melee spell attack. On a hit, the target takes 3d10 necrotic damage.',
        element: 'necrotic',
        diceRoll: '3d10',
        damageType: 'necrotic',
        requiresConcentration: false,
        classes: ['Cleric'],
    },
    {
        name: 'Jump',
        level: 1,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a creature. The creature\'s jump distance is tripled until the spell ends.',
        requiresConcentration: false,
        classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Longstrider',
        level: 1,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a creature. The target\'s speed increases by 10 feet until the spell ends.',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Ranger', 'Wizard', 'Artificer'],
    },
    {
        name: 'Mage Armor',
        level: 1,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a willing creature who isn\'t wearing armor, and a protective magical force surrounds it. Base AC becomes 13 + Dex modifier.',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Magic Missile',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You create three glowing darts of magical force. Each dart deals 1d4+1 force damage.',
        element: 'force',
        diceRoll: '3d4+3',
        damageType: 'force',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Protection from Evil and Good',
        level: 1,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'One willing creature you touch is protected against aberrations, celestials, elementals, fey, fiends, and undead.',
        requiresConcentration: true,
        classes: ['Cleric', 'Paladin', 'Warlock', 'Wizard'],
    },
    {
        name: 'Shield',
        level: 1,
        school: 'Abjuration',
        castingTime: '1 reaction',
        range: 'Self',
        components: 'V, S',
        description: 'An invisible barrier of magical force appears and protects you. You have a +5 bonus to AC.',
        element: 'force',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Silent Image',
        level: 1,
        school: 'Illusion',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You create the image of an object, a creature, or some other visible phenomenon.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Sleep',
        level: 1,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'Creatures within a 20-foot-radius sphere are affected in ascending order of their current hit points.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Speak with Animals',
        level: 1,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'You gain the ability to comprehend and verbally communicate with beasts for the duration.',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Ranger'],
    },
    {
        name: 'Thunderwave',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Self (15-foot cube)',
        components: 'V, S',
        description: 'A wave of thunderous force sweeps out from you. Each creature takes 2d8 thunder damage on a failed save and is pushed 10 feet.',
        element: 'thunder',
        diceRoll: '2d8',
        damageType: 'thunder',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Unseen Servant',
        level: 1,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'This spell creates an invisible, mindless, shapeless force that performs simple tasks at your command.',
        requiresConcentration: false,
        classes: ['Bard', 'Warlock', 'Wizard'],
    },

    // Level 2
    {
        name: 'Aid',
        level: 2,
        school: 'Abjuration',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'Choose up to three creatures. Each target\'s hit point maximum and current hit points increase by 5 for the duration.',
        element: 'healing',
        requiresConcentration: false,
        classes: ['Cleric', 'Paladin', 'Artificer'],
    },
    {
        name: 'Alter Self',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'You assume a different form. Choose Aquatic Adaptation, Change Appearance, or Natural Weapons.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Arcane Lock',
        level: 2,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a closed door, window, gate, chest, or other entryway, and it becomes locked for the duration.',
        requiresConcentration: false,
        classes: ['Wizard', 'Artificer'],
    },
    {
        name: 'Barkskin',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'The target\'s skin has a rough, bark-like appearance, and the target\'s AC can\'t be less than 16.',
        requiresConcentration: true,
        classes: ['Druid', 'Ranger'],
    },
    {
        name: 'Blindness/Deafness',
        level: 2,
        school: 'Necromancy',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V',
        description: 'Choose one creature. On a failed Constitution save, it is blinded or deafened (your choice) for the duration.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Blur',
        level: 2,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Self',
        components: 'V',
        description: 'Your body becomes blurred. Any creature has disadvantage on attack rolls against you.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Calm Emotions',
        level: 2,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S',
        description: 'You attempt to suppress strong emotions in a group of people.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric'],
    },
    {
        name: 'Cloud of Daggers',
        level: 2,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You fill the air with spinning daggers in a cube 5 feet on each side. A creature takes 4d4 slashing damage.',
        element: 'slashing',
        diceRoll: '4d4',
        damageType: 'slashing',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Darkness',
        level: 2,
        school: 'Evocation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, M',
        description: 'Magical darkness spreads from a point you choose to fill a 15-foot-radius sphere.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Darkvision',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a willing creature to grant it darkvision out to a range of 60 feet.',
        requiresConcentration: false,
        classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Enhance Ability',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a creature and bestow upon it a magical enhancement (Bull\'s Strength, Cat\'s Grace, etc.).',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Artificer'],
    },
    {
        name: 'Enlarge/Reduce',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'You cause a creature or an object to grow larger or smaller for the duration.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Flaming Sphere',
        level: 2,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'A 5-foot-diameter sphere of fire appears. Any creature that ends its turn within 5 feet must make a Dexterity save or take 2d6 fire damage.',
        element: 'fire',
        diceRoll: '2d6',
        damageType: 'fire',
        requiresConcentration: true,
        classes: ['Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Gentle Repose',
        level: 2,
        school: 'Necromancy',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a corpse. For the duration, the target is protected from decay and can\'t become undead.',
        requiresConcentration: false,
        classes: ['Cleric', 'Paladin', 'Wizard'],
    },
    {
        name: 'Gust of Wind',
        level: 2,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Self (60-foot line)',
        components: 'V, S, M',
        description: 'A line of strong wind 60 feet long and 10 feet wide blasts from you.',
        requiresConcentration: true,
        classes: ['Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Hold Person',
        level: 2,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'Choose a humanoid. It must succeed on a Wisdom save or be paralyzed for the duration.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Invisibility',
        level: 2,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'A creature you touch becomes invisible until the spell ends.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Knock',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V',
        description: 'Choose an object. A loud knock is heard, and the object is unlocked or opened.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Levitate',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'One creature or object rises vertically, up to 20 feet, and remains suspended for the duration.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Mirror Image',
        level: 2,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'Three illusory duplicates of yourself appear in your space.',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Misty Step',
        level: 2,
        school: 'Conjuration',
        castingTime: '1 bonus action',
        range: 'Self',
        components: 'V',
        description: 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Pass without Trace',
        level: 2,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S, M',
        description: 'A veil of shadows and silence radiates from you. Each creature you choose within 30 feet has a +10 bonus to Stealth checks.',
        requiresConcentration: true,
        classes: ['Druid', 'Ranger'],
    },
    {
        name: 'Scorching Ray',
        level: 2,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You create three rays of fire and hurl them at targets within range.',
        element: 'fire',
        diceRoll: '2d6',
        damageType: 'fire',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'See Invisibility',
        level: 2,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S, M',
        description: 'For the duration, you see invisible creatures and objects as if they were visible.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Shatter',
        level: 2,
        school: 'Evocation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'A sudden loud ringing noise erupts. Each creature in a 10-foot-radius sphere takes 3d8 thunder damage on a failed save.',
        element: 'thunder',
        diceRoll: '3d8',
        damageType: 'thunder',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Spider Climb',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'One willing creature gains the ability to move up, down, and across vertical surfaces and ceilings.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Spiritual Weapon',
        level: 2,
        school: 'Evocation',
        castingTime: '1 bonus action',
        range: '60 ft',
        components: 'V, S',
        description: 'You create a floating, spectral weapon. On a hit, it deals 1d8 + spellcasting modifier force damage.',
        element: 'force',
        diceRoll: '1d8',
        damageType: 'force',
        requiresConcentration: false,
        classes: ['Cleric'],
    },
    {
        name: 'Suggestion',
        level: 2,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, M',
        description: 'You suggest a course of activity and magically influence a creature you can see within range.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Web',
        level: 2,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You conjure a mass of thick, sticky webbing. The webs are difficult terrain and lightly obscure their area.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },

    // Level 3
    {
        name: 'Animate Dead',
        level: 3,
        school: 'Necromancy',
        castingTime: '1 minute',
        range: '10 ft',
        components: 'V, S, M',
        description: 'This spell creates an undead servant from a pile of bones or a corpse.',
        requiresConcentration: false,
        classes: ['Cleric', 'Wizard'],
    },
    {
        name: 'Bestow Curse',
        level: 3,
        school: 'Necromancy',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'You touch a creature, and it must succeed on a Wisdom save or become cursed for the duration.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Wizard'],
    },
    {
        name: 'Blink',
        level: 3,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'Roll a d20 at the end of each of your turns. On 11 or higher, you vanish to the Ethereal Plane.',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Clairvoyance',
        level: 3,
        school: 'Divination',
        castingTime: '10 minutes',
        range: '1 mile',
        components: 'V, S, M',
        description: 'You create an invisible sensor within range. You can see and hear through it.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Counterspell',
        level: 3,
        school: 'Abjuration',
        castingTime: '1 reaction',
        range: '60 ft',
        components: 'S',
        description: 'You attempt to interrupt a creature in the process of casting a spell. If it is 3rd level or lower, its spell fails.',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Create Food and Water',
        level: 3,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'You create 45 pounds of food and 30 gallons of water, enough to sustain up to fifteen humanoids for 24 hours.',
        requiresConcentration: false,
        classes: ['Cleric', 'Paladin', 'Artificer'],
    },
    {
        name: 'Dispel Magic',
        level: 3,
        school: 'Abjuration',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'Choose one creature, object, or magical effect. Any spell of 3rd level or lower on the target ends.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Fear',
        level: 3,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Self (30-foot cone)',
        components: 'V, S, M',
        description: 'Each creature in a 30-foot cone must succeed on a Wisdom save or drop what it\'s holding and become frightened.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Fireball',
        level: 3,
        school: 'Evocation',
        castingTime: '1 action',
        range: '150 ft',
        components: 'V, S, M',
        description: 'A bright streak flashes to a point you choose and blossoms into an explosion of flame. Each creature in a 20-foot-radius sphere takes 8d6 fire damage.',
        element: 'fire',
        diceRoll: '8d6',
        damageType: 'fire',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Fly',
        level: 3,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a willing creature. The target gains a flying speed of 60 feet for the duration.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Gaseous Form',
        level: 3,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'A willing creature you touch transforms into a misty cloud for the duration.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Haste',
        level: 3,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'The target\'s speed is doubled, it gains +2 to AC, advantage on Dex saves, and an additional action on each turn.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Hypnotic Pattern',
        level: 3,
        school: 'Illusion',
        castingTime: '1 action',
        range: '120 ft',
        components: 'S, M',
        description: 'You create a twisting pattern of colors. Each creature in a 30-foot cube that sees it must make a Wisdom save or be charmed.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: "Leomund's Tiny Hut",
        level: 3,
        school: 'Evocation',
        castingTime: '1 minute',
        range: 'Self (10-foot-radius hemisphere)',
        components: 'V, S, M',
        description: 'A 10-foot-radius immobile dome of force springs into existence around and above you.',
        requiresConcentration: false,
        classes: ['Bard', 'Wizard'],
    },
    {
        name: 'Lightning Bolt',
        level: 3,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Self (100-foot line)',
        components: 'V, S, M',
        description: 'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you. Each creature in the line takes 8d6 lightning damage.',
        element: 'lightning',
        diceRoll: '8d6',
        damageType: 'lightning',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Magic Circle',
        level: 3,
        school: 'Abjuration',
        castingTime: '1 minute',
        range: '10 ft',
        components: 'V, S, M',
        description: 'You create a 10-foot-radius, 20-foot-tall cylinder of magical energy.',
        requiresConcentration: false,
        classes: ['Cleric', 'Paladin', 'Warlock', 'Wizard'],
    },
    {
        name: 'Major Image',
        level: 3,
        school: 'Illusion',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'You create the image of an object, a creature, or some other visible phenomenon no larger than a 20-foot cube.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Nondetection',
        level: 3,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a willing creature and prevent it from being detected by divination magic.',
        requiresConcentration: false,
        classes: ['Bard', 'Ranger', 'Wizard'],
    },
    {
        name: 'Remove Curse',
        level: 3,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'At your touch, all curses affecting one creature or object end.',
        requiresConcentration: false,
        classes: ['Cleric', 'Paladin', 'Warlock', 'Wizard'],
    },
    {
        name: 'Revivify',
        level: 3,
        school: 'Necromancy',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a creature that has died within the last minute. That creature returns to life with 1 hit point.',
        element: 'healing',
        requiresConcentration: false,
        classes: ['Cleric', 'Paladin', 'Artificer'],
    },
    {
        name: 'Sending',
        level: 3,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Unlimited',
        components: 'V, S, M',
        description: 'You send a short message of twenty-five words or less to a creature with which you are familiar.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Wizard'],
    },
    {
        name: 'Slow',
        level: 3,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'You alter time around up to six creatures in a 40-foot cube. Each target must succeed on a Wisdom save or be affected.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Speak with Dead',
        level: 3,
        school: 'Necromancy',
        castingTime: '1 action',
        range: '10 ft',
        components: 'V, S, M',
        description: 'You grant the semblance of life and intelligence to a corpse, allowing it to answer questions.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric'],
    },
    {
        name: 'Spirit Guardians',
        level: 3,
        school: 'Conjuration',
        castingTime: '1 action',
        range: 'Self (15-foot radius)',
        components: 'V, S, M',
        description: 'Spirits flit around you to a distance of 15 feet. When a creature enters the area, it takes 3d8 radiant or necrotic damage.',
        element: 'radiant',
        diceRoll: '3d8',
        damageType: 'radiant',
        requiresConcentration: true,
        classes: ['Cleric'],
    },
    {
        name: 'Stinking Cloud',
        level: 3,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'You create a 20-foot-radius sphere of yellow, nauseating gas. The cloud spreads around corners.',
        element: 'poison',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Tongues',
        level: 3,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, M',
        description: 'This spell grants the creature you touch the ability to understand any spoken language it hears.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Water Breathing',
        level: 3,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'This spell grants up to ten willing creatures the ability to breathe underwater.',
        requiresConcentration: false,
        classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    },

    // Level 4
    {
        name: 'Banishment',
        level: 4,
        school: 'Abjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You attempt to send one creature to another plane of existence. The target must succeed on a Charisma save or be banished.',
        requiresConcentration: true,
        classes: ['Cleric', 'Paladin', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Black Tentacles',
        level: 4,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'Squirming, ebony tentacles fill a 20-foot square. A creature in the area takes 3d6 bludgeoning damage and is restrained.',
        element: 'bludgeoning',
        diceRoll: '3d6',
        damageType: 'bludgeoning',
        requiresConcentration: true,
        classes: ['Wizard'],
    },
    {
        name: 'Charm Monster',
        level: 4,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'You attempt to charm a creature you can see within range.',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Confusion',
        level: 4,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'Each creature in a 10-foot-radius sphere must succeed on a Wisdom save or be affected by confusion.',
        requiresConcentration: true,
        classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Conjure Woodland Beings',
        level: 4,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You summon fey creatures that appear in unoccupied spaces that you can see within range.',
        requiresConcentration: true,
        classes: ['Druid', 'Ranger'],
    },
    {
        name: 'Death Ward',
        level: 4,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'You touch a creature and grant it protection from death. The first time it would drop to 0 HP, it drops to 1 HP instead.',
        element: 'healing',
        requiresConcentration: false,
        classes: ['Cleric', 'Paladin'],
    },
    {
        name: 'Dimension Door',
        level: 4,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '500 ft',
        components: 'V',
        description: 'You teleport yourself from your current location to any other spot within range.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Divination',
        level: 4,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S, M',
        description: 'Your magic and an offering put you in contact with a god or a god\'s servants. You ask a single question.',
        requiresConcentration: false,
        classes: ['Cleric', 'Druid', 'Wizard'],
    },
    {
        name: 'Freedom of Movement',
        level: 4,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'The target\'s movement is unaffected by difficult terrain, and spells can\'t reduce its speed or paralyze it.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Ranger', 'Artificer'],
    },
    {
        name: 'Greater Invisibility',
        level: 4,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'You or a creature you touch becomes invisible until the spell ends.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Ice Storm',
        level: 4,
        school: 'Evocation',
        castingTime: '1 action',
        range: '300 ft',
        components: 'V, S, M',
        description: 'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder. Deals 2d8 bludgeoning + 4d6 cold damage.',
        element: 'cold',
        diceRoll: '2d8 + 4d6',
        damageRoll: '4d6',
        damageType: 'cold',
        requiresConcentration: false,
        classes: ['Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Phantasmal Killer',
        level: 4,
        school: 'Illusion',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You tap into the nightmares of a creature you can see and create an illusory manifestation of its deepest fears.',
        element: 'psychic',
        diceRoll: '4d10',
        damageType: 'psychic',
        requiresConcentration: true,
        classes: ['Wizard'],
    },
    {
        name: 'Planar Binding',
        level: 4,
        school: 'Abjuration',
        castingTime: '1 hour',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You attempt to bind a celestial, an elemental, a fey, or a fiend to your service.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Wizard'],
    },
    {
        name: 'Polymorph',
        level: 4,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'This spell transforms a creature that you can see within range into a new form.',
        requiresConcentration: true,
        classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Stone Shape',
        level: 4,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a stone object and form it into any shape that suits your purpose.',
        requiresConcentration: false,
        classes: ['Cleric', 'Druid', 'Wizard', 'Artificer'],
    },
    {
        name: 'Wall of Fire',
        level: 4,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'You create a wall of fire on a solid surface. One side of the wall deals 5d8 fire damage to creatures within 10 feet.',
        element: 'fire',
        diceRoll: '5d8',
        damageType: 'fire',
        requiresConcentration: true,
        classes: ['Druid', 'Sorcerer', 'Wizard'],
    },

    // Level 5
    {
        name: 'Animate Objects',
        level: 5,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'Objects come to life at your command. Choose up to ten nonmagical objects within range.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Cone of Cold',
        level: 5,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Self (60-foot cone)',
        components: 'V, S, M',
        description: 'A blast of cold air erupts from your hands. Each creature in a 60-foot cone takes 8d8 cold damage.',
        element: 'cold',
        diceRoll: '8d8',
        damageType: 'cold',
        requiresConcentration: false,
        classes: ['Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Contact Other Plane',
        level: 5,
        school: 'Divination',
        castingTime: '1 minute',
        range: 'Self',
        components: 'V',
        description: 'You mentally contact a demigod, the spirit of a long-dead sage, or some other mysterious entity.',
        requiresConcentration: false,
        classes: ['Warlock', 'Wizard'],
    },
    {
        name: 'Dominate Person',
        level: 5,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S',
        description: 'You attempt to beguile a humanoid. It must succeed on a Wisdom save or be charmed by you for the duration.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Dream',
        level: 5,
        school: 'Illusion',
        castingTime: '1 minute',
        range: 'Special',
        components: 'V, S, M',
        description: 'This spell shapes a creature\'s dreams. Choose a creature known to you as the target.',
        requiresConcentration: false,
        classes: ['Bard', 'Warlock', 'Wizard'],
    },
    {
        name: 'Geas',
        level: 5,
        school: 'Enchantment',
        castingTime: '1 minute',
        range: '60 ft',
        components: 'V',
        description: 'You place a magical command on a creature, forcing it to carry out some service.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Wizard'],
    },
    {
        name: 'Hold Monster',
        level: 5,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'Choose a creature. It must succeed on a Wisdom save or be paralyzed for the duration. This spell has no effect on undead.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Legend Lore',
        level: 5,
        school: 'Divination',
        castingTime: '10 minutes',
        range: 'Self',
        components: 'V, S, M',
        description: 'Name or describe a person, place, or object. The spell brings to your mind a brief summary of significant lore.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Wizard'],
    },
    {
        name: 'Mass Cure Wounds',
        level: 5,
        school: 'Evocation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S',
        description: 'A wave of healing energy washes out from a point of your choice. Each target regains 3d8 + spellcasting modifier hit points.',
        element: 'healing',
        diceRoll: '3d8',
        damageType: 'healing',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid'],
    },
    {
        name: 'Mislead',
        level: 5,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Self',
        components: 'S',
        description: 'You become invisible at the same time that an illusory double of you appears where you are standing.',
        requiresConcentration: true,
        classes: ['Bard', 'Wizard'],
    },
    {
        name: 'Modify Memory',
        level: 5,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'You attempt to reshape another creature\'s memories.',
        requiresConcentration: true,
        classes: ['Bard', 'Wizard'],
    },
    {
        name: 'Passwall',
        level: 5,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'A passage appears at a point of your choice that you can see on a wooden, plaster, or stone surface.',
        requiresConcentration: false,
        classes: ['Wizard'],
    },
    {
        name: 'Raise Dead',
        level: 5,
        school: 'Necromancy',
        castingTime: '1 hour',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You return a dead creature you touch to life, provided it has been dead no longer than 10 days.',
        element: 'healing',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Paladin'],
    },
    {
        name: 'Scrying',
        level: 5,
        school: 'Divination',
        castingTime: '10 minutes',
        range: 'Self',
        components: 'V, S, M',
        description: 'You can see and hear a particular creature you choose that is on the same plane of existence as you.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Druid', 'Warlock', 'Wizard'],
    },
    {
        name: 'Seeming',
        level: 5,
        school: 'Illusion',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'This spell allows you to change the appearance of any number of creatures that you can see within range.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Teleportation Circle',
        level: 5,
        school: 'Conjuration',
        castingTime: '1 minute',
        range: '10 ft',
        components: 'V, S, M',
        description: 'You draw a 10-foot-diameter circle on the ground inscribed with sigils that link your location to a permanent teleportation circle.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Wall of Force',
        level: 5,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'An invisible wall of force springs into existence at a point you choose within range.',
        element: 'force',
        requiresConcentration: true,
        classes: ['Wizard'],
    },
    {
        name: 'Wall of Stone',
        level: 5,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'A nonmagical wall of solid stone springs into existence at a point you choose within range.',
        requiresConcentration: true,
        classes: ['Druid', 'Sorcerer', 'Wizard', 'Artificer'],
    },
];