import { SpellData } from './types';

export const CANTRIPS: SpellData[] = [
    {
        name: 'Acid Splash',
        level: 0,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S',
        description: 'You hurl a bubble of acid. Choose one creature within range, or two creatures within 5 feet of each other.',
        element: 'acid',
        diceRoll: '1d6',
        damageType: 'acid',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Blade Ward',
        level: 0,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Chill Touch',
        level: 0,
        school: 'Necromancy',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You create a ghostly, skeletal hand that attacks a creature.',
        element: 'necrotic',
        diceRoll: '1d8',
        damageType: 'necrotic',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Dancing Lights',
        level: 0,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'You create up to four torch-sized lights within range.',
        element: 'radiant',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Fire Bolt',
        level: 0,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You hurl a mote of fire at a creature or object within range.',
        element: 'fire',
        diceRoll: '1d10',
        damageType: 'fire',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Guidance',
        level: 0,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice.',
        requiresConcentration: true,
        classes: ['Cleric', 'Druid', 'Artificer'],
    },
    {
        name: 'Light',
        level: 0,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, M',
        description: 'You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light.',
        element: 'radiant',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Mage Hand',
        level: 0,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'A spectral, floating hand appears at a point you choose within range.',
        element: 'force',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Mending',
        level: 0,
        school: 'Transmutation',
        castingTime: '1 minute',
        range: 'Touch',
        components: 'V, S, M',
        description: 'This spell repairs a single break or tear in an object you touch.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Message',
        level: 0,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'You point your finger toward a creature within range and whisper a message.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Minor Illusion',
        level: 0,
        school: 'Illusion',
        castingTime: '1 action',
        range: '30 ft',
        components: 'S, M',
        description: 'You create a sound or an image of an object within range that lasts for the duration.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Poison Spray',
        level: 0,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '10 ft',
        components: 'V, S',
        description: 'You project a puff of noxious gas.',
        element: 'poison',
        diceRoll: '1d12',
        damageType: 'poison',
        requiresConcentration: false,
        classes: ['Druid', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Prestidigitation',
        level: 0,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '10 ft',
        components: 'V, S',
        description: 'This spell is a minor magical trick that novice spellcasters use for practice.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Ray of Frost',
        level: 0,
        school: 'Evocation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S',
        description: 'A frigid beam of blue-white light streaks toward a creature within range.',
        element: 'cold',
        diceRoll: '1d8',
        damageType: 'cold',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Shillelagh',
        level: 0,
        school: 'Transmutation',
        castingTime: '1 bonus action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'The wood of a club or quarterstaff you are holding is imbued with nature\'s power.',
        requiresConcentration: false,
        classes: ['Druid'],
    },
    {
        name: 'Spare the Dying',
        level: 0,
        school: 'Necromancy',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'You touch a living creature that has 0 hit points. The creature becomes stable.',
        element: 'healing',
        requiresConcentration: false,
        classes: ['Cleric', 'Artificer'],
    },
    {
        name: 'Thaumaturgy',
        level: 0,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V',
        description: 'You manifest a minor wonder, a sign of supernatural power, within range.',
        requiresConcentration: false,
        classes: ['Cleric'],
    },
    {
        name: 'True Strike',
        level: 0,
        school: 'Divination',
        castingTime: '1 action',
        range: '30 ft',
        components: 'S',
        description: 'You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target\'s defenses.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
];