import { SpellData } from './types';

export const LEVEL_4_SPELLS: SpellData[] = [
    {
        name: 'Banishment',
        level: 4,
        school: 'Abjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You attempt to send one creature to another plane of existence. The target must succeed on a Charisma save or be banished.',
        requiresConcentration: true,
        classes: ['Cleric', 'Paladin', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Black Tentacles',
        level: 4,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'Squirming, ebony tentacles fill a 20-foot square. A creature in the area takes 3d6 bludgeoning damage and is restrained.',
        element: 'bludgeoning',
        diceRoll: '3d6',
        damageType: 'bludgeoning',
        requiresConcentration: true,
        classes: ['Wizard'],
    },
    {
        name: 'Charm Monster',
        level: 4,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'You attempt to charm a creature you can see within range.',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Confusion',
        level: 4,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'Each creature in a 10-foot-radius sphere must succeed on a Wisdom save or be affected by confusion.',
        requiresConcentration: true,
        classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Conjure Woodland Beings',
        level: 4,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You summon fey creatures that appear in unoccupied spaces that you can see within range.',
        requiresConcentration: true,
        classes: ['Druid', 'Ranger'],
    },
    {
        name: 'Death Ward',
        level: 4,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'You touch a creature and grant it protection from death. The first time it would drop to 0 HP, it drops to 1 HP instead.',
        element: 'healing',
        requiresConcentration: false,
        classes: ['Cleric', 'Paladin'],
    },
    {
        name: 'Dimension Door',
        level: 4,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '500 ft',
        components: 'V',
        description: 'You teleport yourself from your current location to any other spot within range.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Divination',
        level: 4,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S, M',
        description: 'Your magic and an offering put you in contact with a god or a god\'s servants. You ask a single question.',
        requiresConcentration: false,
        classes: ['Cleric', 'Druid', 'Wizard'],
    },
    {
        name: 'Freedom of Movement',
        level: 4,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'The target\'s movement is unaffected by difficult terrain, and spells can\'t reduce its speed or paralyze it.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Ranger', 'Artificer'],
    },
    {
        name: 'Greater Invisibility',
        level: 4,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'You or a creature you touch becomes invisible until the spell ends.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Ice Storm',
        level: 4,
        school: 'Evocation',
        castingTime: '1 action',
        range: '300 ft',
        components: 'V, S, M',
        description: 'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder. Deals 2d8 bludgeoning + 4d6 cold damage.',
        element: 'cold',
        diceRoll: '2d8 + 4d6',
        damageRoll: '4d6',
        damageType: 'cold',
        requiresConcentration: false,
        classes: ['Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Phantasmal Killer',
        level: 4,
        school: 'Illusion',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You tap into the nightmares of a creature you can see and create an illusory manifestation of its deepest fears.',
        element: 'psychic',
        diceRoll: '4d10',
        damageType: 'psychic',
        requiresConcentration: true,
        classes: ['Wizard'],
    },
    {
        name: 'Planar Binding',
        level: 4,
        school: 'Abjuration',
        castingTime: '1 hour',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You attempt to bind a celestial, an elemental, a fey, or a fiend to your service.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Wizard'],
    },
    {
        name: 'Polymorph',
        level: 4,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'This spell transforms a creature that you can see within range into a new form.',
        requiresConcentration: true,
        classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Stone Shape',
        level: 4,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a stone object and form it into any shape that suits your purpose.',
        requiresConcentration: false,
        classes: ['Cleric', 'Druid', 'Wizard', 'Artificer'],
    },
    {
        name: 'Wall of Fire',
        level: 4,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'You create a wall of fire on a solid surface. One side of the wall deals 5d8 fire damage to creatures within 10 feet.',
        element: 'fire',
        diceRoll: '5d8',
        damageType: 'fire',
        requiresConcentration: true,
        classes: ['Druid', 'Sorcerer', 'Wizard'],
    },
];