import { SpellData } from './types';

export const LEVEL_2_SPELLS: SpellData[] = [
    {
        name: 'Aid',
        level: 2,
        school: 'Abjuration',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'Choose up to three creatures. Each target\'s hit point maximum and current hit points increase by 5 for the duration.',
        element: 'healing',
        requiresConcentration: false,
        classes: ['Cleric', 'Paladin', 'Artificer'],
    },
    {
        name: 'Alter Self',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'You assume a different form. Choose Aquatic Adaptation, Change Appearance, or Natural Weapons.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Arcane Lock',
        level: 2,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a closed door, window, gate, chest, or other entryway, and it becomes locked for the duration.',
        requiresConcentration: false,
        classes: ['Wizard', 'Artificer'],
    },
    {
        name: 'Barkskin',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'The target\'s skin has a rough, bark-like appearance, and the target\'s AC can\'t be less than 16.',
        requiresConcentration: true,
        classes: ['Druid', 'Ranger'],
    },
    {
        name: 'Blindness/Deafness',
        level: 2,
        school: 'Necromancy',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V',
        description: 'Choose one creature. On a failed Constitution save, it is blinded or deafened (your choice) for the duration.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Blur',
        level: 2,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Self',
        components: 'V',
        description: 'Your body becomes blurred. Any creature has disadvantage on attack rolls against you.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Calm Emotions',
        level: 2,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S',
        description: 'You attempt to suppress strong emotions in a group of people.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric'],
    },
    {
        name: 'Cloud of Daggers',
        level: 2,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You fill the air with spinning daggers in a cube 5 feet on each side. A creature takes 4d4 slashing damage.',
        element: 'slashing',
        diceRoll: '4d4',
        damageType: 'slashing',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Darkness',
        level: 2,
        school: 'Evocation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, M',
        description: 'Magical darkness spreads from a point you choose to fill a 15-foot-radius sphere.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Darkvision',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a willing creature to grant it darkvision out to a range of 60 feet.',
        requiresConcentration: false,
        classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Enhance Ability',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a creature and bestow upon it a magical enhancement (Bull\'s Strength, Cat\'s Grace, etc.).',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Artificer'],
    },
    {
        name: 'Enlarge/Reduce',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'You cause a creature or an object to grow larger or smaller for the duration.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Flaming Sphere',
        level: 2,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'A 5-foot-diameter sphere of fire appears. Any creature that ends its turn within 5 feet must make a Dexterity save or take 2d6 fire damage.',
        element: 'fire',
        diceRoll: '2d6',
        damageType: 'fire',
        requiresConcentration: true,
        classes: ['Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Gentle Repose',
        level: 2,
        school: 'Necromancy',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a corpse. For the duration, the target is protected from decay and can\'t become undead.',
        requiresConcentration: false,
        classes: ['Cleric', 'Paladin', 'Wizard'],
    },
    {
        name: 'Gust of Wind',
        level: 2,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Self (60-foot line)',
        components: 'V, S, M',
        description: 'A line of strong wind 60 feet long and 10 feet wide blasts from you.',
        requiresConcentration: true,
        classes: ['Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Hold Person',
        level: 2,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'Choose a humanoid. It must succeed on a Wisdom save or be paralyzed for the duration.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Invisibility',
        level: 2,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'A creature you touch becomes invisible until the spell ends.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Knock',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V',
        description: 'Choose an object. A loud knock is heard, and the object is unlocked or opened.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Levitate',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'One creature or object rises vertically, up to 20 feet, and remains suspended for the duration.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Mirror Image',
        level: 2,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'Three illusory duplicates of yourself appear in your space.',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Misty Step',
        level: 2,
        school: 'Conjuration',
        castingTime: '1 bonus action',
        range: 'Self',
        components: 'V',
        description: 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Pass without Trace',
        level: 2,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S, M',
        description: 'A veil of shadows and silence radiates from you. Each creature you choose within 30 feet has a +10 bonus to Stealth checks.',
        requiresConcentration: true,
        classes: ['Druid', 'Ranger'],
    },
    {
        name: 'Scorching Ray',
        level: 2,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You create three rays of fire and hurl them at targets within range.',
        element: 'fire',
        diceRoll: '2d6',
        damageType: 'fire',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'See Invisibility',
        level: 2,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S, M',
        description: 'For the duration, you see invisible creatures and objects as if they were visible.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Shatter',
        level: 2,
        school: 'Evocation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'A sudden loud ringing noise erupts. Each creature in a 10-foot-radius sphere takes 3d8 thunder damage on a failed save.',
        element: 'thunder',
        diceRoll: '3d8',
        damageType: 'thunder',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Spider Climb',
        level: 2,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'One willing creature gains the ability to move up, down, and across vertical surfaces and ceilings.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Spiritual Weapon',
        level: 2,
        school: 'Evocation',
        castingTime: '1 bonus action',
        range: '60 ft',
        components: 'V, S',
        description: 'You create a floating, spectral weapon. On a hit, it deals 1d8 + spellcasting modifier force damage.',
        element: 'force',
        diceRoll: '1d8',
        damageType: 'force',
        requiresConcentration: false,
        classes: ['Cleric'],
    },
    {
        name: 'Suggestion',
        level: 2,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, M',
        description: 'You suggest a course of activity and magically influence a creature you can see within range.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Web',
        level: 2,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You conjure a mass of thick, sticky webbing. The webs are difficult terrain and lightly obscure their area.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
];