import { SpellData } from './types';

export const LEVEL_1_SPELLS: SpellData[] = [
    {
        name: 'Alarm',
        level: 1,
        school: 'Abjuration',
        castingTime: '1 minute',
        range: '30 ft',
        components: 'V, S, M',
        description: 'You set an alarm against unwanted intrusion.',
        requiresConcentration: false,
        classes: ['Ranger', 'Wizard', 'Artificer'],
    },
    {
        name: 'Animal Friendship',
        level: 1,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'You attempt to charm a beast that you can see within range.',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Ranger'],
    },
    {
        name: 'Bane',
        level: 1,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'Up to three creatures must make Charisma saving throws. On a failure, they subtract 1d4 from attack rolls and saving throws.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Warlock'],
    },
    {
        name: 'Bless',
        level: 1,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'You bless up to three creatures. They add 1d4 to attack rolls and saving throws.',
        requiresConcentration: true,
        classes: ['Cleric', 'Paladin'],
    },
    {
        name: 'Burning Hands',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Self (15-foot cone)',
        components: 'V, S',
        description: 'A thin sheet of flames shoots forth from your outstretched fingertips.',
        element: 'fire',
        diceRoll: '3d6',
        damageType: 'fire',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Charm Person',
        level: 1,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'You attempt to charm a humanoid you can see within range.',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Chromatic Orb',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'You hurl a sphere of energy. Choose acid, cold, fire, lightning, poison, or thunder.',
        element: 'force',
        diceRoll: '3d8',
        damageType: 'varies',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Cure Wounds',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'A creature you touch regains hit points equal to 1d8 + your spellcasting ability modifier.',
        element: 'healing',
        diceRoll: '1d8',
        damageType: 'healing',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Artificer'],
    },
    {
        name: 'Detect Magic',
        level: 1,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'For the duration, you sense the presence of magic within 30 feet of you.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Disguise Self',
        level: 1,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'You make yourself—including your clothing, armor, weapons, and other belongings—look different.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Expeditious Retreat',
        level: 1,
        school: 'Transmutation',
        castingTime: '1 bonus action',
        range: 'Self',
        components: 'V, S',
        description: 'You can take the Dash action as a bonus action on each of your turns until the spell ends.',
        requiresConcentration: true,
        classes: ['Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    },
    {
        name: 'Faerie Fire',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V',
        description: 'Each object in a 20-foot cube is outlined in light. Creatures in the area are also outlined if they fail a Dexterity saving throw.',
        element: 'radiant',
        requiresConcentration: true,
        classes: ['Bard', 'Druid'],
    },
    {
        name: 'False Life',
        level: 1,
        school: 'Necromancy',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S, M',
        description: 'You gain 1d4+4 temporary hit points for the duration.',
        element: 'necrotic',
        diceRoll: '1d4+4',
        damageType: 'healing',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Feather Fall',
        level: 1,
        school: 'Transmutation',
        castingTime: '1 reaction',
        range: '60 ft',
        components: 'V, M',
        description: 'Choose up to five falling creatures within range. Their rate of descent slows to 60 feet per round.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Find Familiar',
        level: 1,
        school: 'Conjuration',
        castingTime: '1 hour',
        range: '10 ft',
        components: 'V, S, M',
        description: 'You gain the service of a familiar, a spirit that takes an animal form you choose.',
        requiresConcentration: false,
        classes: ['Wizard'],
    },
    {
        name: 'Fog Cloud',
        level: 1,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You create a 20-foot-radius sphere of fog. The sphere spreads around corners, and its area is heavily obscured.',
        requiresConcentration: true,
        classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Grease',
        level: 1,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'Slick grease covers the ground in a 10-foot square and turns it into difficult terrain.',
        requiresConcentration: false,
        classes: ['Wizard', 'Artificer'],
    },
    {
        name: 'Guiding Bolt',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'A flash of light streaks toward a creature. On a hit, the target takes 4d6 radiant damage, and the next attack roll against it has advantage.',
        element: 'radiant',
        diceRoll: '4d6',
        damageType: 'radiant',
        requiresConcentration: false,
        classes: ['Cleric'],
    },
    {
        name: 'Healing Word',
        level: 1,
        school: 'Evocation',
        castingTime: '1 bonus action',
        range: '60 ft',
        components: 'V',
        description: 'A creature of your choice regains hit points equal to 1d4 + your spellcasting ability modifier.',
        element: 'healing',
        diceRoll: '1d4',
        damageType: 'healing',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid'],
    },
    {
        name: 'Hellish Rebuke',
        level: 1,
        school: 'Evocation',
        castingTime: '1 reaction',
        range: '60 ft',
        components: 'V, S',
        description: 'The creature that damaged you is momentarily surrounded by hellish flames. It takes 2d10 fire damage on a failed save.',
        element: 'fire',
        diceRoll: '2d10',
        damageType: 'fire',
        requiresConcentration: false,
        classes: ['Warlock'],
    },
    {
        name: 'Identify',
        level: 1,
        school: 'Divination',
        castingTime: '1 minute',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You choose one object that you must touch throughout the casting. If it is a magic item, you learn its properties.',
        requiresConcentration: false,
        classes: ['Bard', 'Wizard', 'Artificer'],
    },
    {
        name: 'Illusory Script',
        level: 1,
        school: 'Illusion',
        castingTime: '1 minute',
        range: 'Touch',
        components: 'S, M',
        description: 'You write on parchment and imbue it with a potent illusion that lasts for the duration.',
        requiresConcentration: false,
        classes: ['Bard', 'Warlock', 'Wizard'],
    },
    {
        name: 'Inflict Wounds',
        level: 1,
        school: 'Necromancy',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S',
        description: 'Make a melee spell attack. On a hit, the target takes 3d10 necrotic damage.',
        element: 'necrotic',
        diceRoll: '3d10',
        damageType: 'necrotic',
        requiresConcentration: false,
        classes: ['Cleric'],
    },
    {
        name: 'Jump',
        level: 1,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a creature. The creature\'s jump distance is tripled until the spell ends.',
        requiresConcentration: false,
        classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Longstrider',
        level: 1,
        school: 'Transmutation',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a creature. The target\'s speed increases by 10 feet until the spell ends.',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Ranger', 'Wizard', 'Artificer'],
    },
    {
        name: 'Mage Armor',
        level: 1,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You touch a willing creature who isn\'t wearing armor, and a protective magical force surrounds it. Base AC becomes 13 + Dex modifier.',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Magic Missile',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'You create three glowing darts of magical force. Each dart deals 1d4+1 force damage.',
        element: 'force',
        diceRoll: '3d4+3',
        damageType: 'force',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Protection from Evil and Good',
        level: 1,
        school: 'Abjuration',
        castingTime: '1 action',
        range: 'Touch',
        components: 'V, S, M',
        description: 'One willing creature you touch is protected against aberrations, celestials, elementals, fey, fiends, and undead.',
        requiresConcentration: true,
        classes: ['Cleric', 'Paladin', 'Warlock', 'Wizard'],
    },
    {
        name: 'Shield',
        level: 1,
        school: 'Abjuration',
        castingTime: '1 reaction',
        range: 'Self',
        components: 'V, S',
        description: 'An invisible barrier of magical force appears and protects you. You have a +5 bonus to AC.',
        element: 'force',
        requiresConcentration: false,
        classes: ['Sorcerer', 'Wizard'],
    },
    {
        name: 'Silent Image',
        level: 1,
        school: 'Illusion',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'You create the image of an object, a creature, or some other visible phenomenon.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Sleep',
        level: 1,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'Creatures within a 20-foot-radius sphere are affected in ascending order of their current hit points.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Speak with Animals',
        level: 1,
        school: 'Divination',
        castingTime: '1 action',
        range: 'Self',
        components: 'V, S',
        description: 'You gain the ability to comprehend and verbally communicate with beasts for the duration.',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Ranger'],
    },
    {
        name: 'Thunderwave',
        level: 1,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Self (15-foot cube)',
        components: 'V, S',
        description: 'A wave of thunderous force sweeps out from you. Each creature takes 2d8 thunder damage on a failed save and is pushed 10 feet.',
        element: 'thunder',
        diceRoll: '2d8',
        damageType: 'thunder',
        requiresConcentration: false,
        classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Unseen Servant',
        level: 1,
        school: 'Conjuration',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S, M',
        description: 'This spell creates an invisible, mindless, shapeless force that performs simple tasks at your command.',
        requiresConcentration: false,
        classes: ['Bard', 'Warlock', 'Wizard'],
    },
];