import { SpellData } from './types';

export const LEVEL_5_SPELLS: SpellData[] = [
    {
        name: 'Animate Objects',
        level: 5,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S',
        description: 'Objects come to life at your command. Choose up to ten nonmagical objects within range.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    },
    {
        name: 'Cone of Cold',
        level: 5,
        school: 'Evocation',
        castingTime: '1 action',
        range: 'Self (60-foot cone)',
        components: 'V, S, M',
        description: 'A blast of cold air erupts from your hands. Each creature in a 60-foot cone takes 8d8 cold damage.',
        element: 'cold',
        diceRoll: '8d8',
        damageType: 'cold',
        requiresConcentration: false,
        classes: ['Druid', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Contact Other Plane',
        level: 5,
        school: 'Divination',
        castingTime: '1 minute',
        range: 'Self',
        components: 'V',
        description: 'You mentally contact a demigod, the spirit of a long-dead sage, or some other mysterious entity.',
        requiresConcentration: false,
        classes: ['Warlock', 'Wizard'],
    },
    {
        name: 'Dominate Person',
        level: 5,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S',
        description: 'You attempt to beguile a humanoid. It must succeed on a Wisdom save or be charmed by you for the duration.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Dream',
        level: 5,
        school: 'Illusion',
        castingTime: '1 minute',
        range: 'Special',
        components: 'V, S, M',
        description: 'This spell shapes a creature\'s dreams. Choose a creature known to you as the target.',
        requiresConcentration: false,
        classes: ['Bard', 'Warlock', 'Wizard'],
    },
    {
        name: 'Geas',
        level: 5,
        school: 'Enchantment',
        castingTime: '1 minute',
        range: '60 ft',
        components: 'V',
        description: 'You place a magical command on a creature, forcing it to carry out some service.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Wizard'],
    },
    {
        name: 'Hold Monster',
        level: 5,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '90 ft',
        components: 'V, S, M',
        description: 'Choose a creature. It must succeed on a Wisdom save or be paralyzed for the duration. This spell has no effect on undead.',
        requiresConcentration: true,
        classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    },
    {
        name: 'Legend Lore',
        level: 5,
        school: 'Divination',
        castingTime: '10 minutes',
        range: 'Self',
        components: 'V, S, M',
        description: 'Name or describe a person, place, or object. The spell brings to your mind a brief summary of significant lore.',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Wizard'],
    },
    {
        name: 'Mass Cure Wounds',
        level: 5,
        school: 'Evocation',
        castingTime: '1 action',
        range: '60 ft',
        components: 'V, S',
        description: 'A wave of healing energy washes out from a point of your choice. Each target regains 3d8 + spellcasting modifier hit points.',
        element: 'healing',
        diceRoll: '3d8',
        damageType: 'healing',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Druid'],
    },
    {
        name: 'Mislead',
        level: 5,
        school: 'Illusion',
        castingTime: '1 action',
        range: 'Self',
        components: 'S',
        description: 'You become invisible at the same time that an illusory double of you appears where you are standing.',
        requiresConcentration: true,
        classes: ['Bard', 'Wizard'],
    },
    {
        name: 'Modify Memory',
        level: 5,
        school: 'Enchantment',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'You attempt to reshape another creature\'s memories.',
        requiresConcentration: true,
        classes: ['Bard', 'Wizard'],
    },
    {
        name: 'Passwall',
        level: 5,
        school: 'Transmutation',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S, M',
        description: 'A passage appears at a point of your choice that you can see on a wooden, plaster, or stone surface.',
        requiresConcentration: false,
        classes: ['Wizard'],
    },
    {
        name: 'Raise Dead',
        level: 5,
        school: 'Necromancy',
        castingTime: '1 hour',
        range: 'Touch',
        components: 'V, S, M',
        description: 'You return a dead creature you touch to life, provided it has been dead no longer than 10 days.',
        element: 'healing',
        requiresConcentration: false,
        classes: ['Bard', 'Cleric', 'Paladin'],
    },
    {
        name: 'Scrying',
        level: 5,
        school: 'Divination',
        castingTime: '10 minutes',
        range: 'Self',
        components: 'V, S, M',
        description: 'You can see and hear a particular creature you choose that is on the same plane of existence as you.',
        requiresConcentration: true,
        classes: ['Bard', 'Cleric', 'Druid', 'Warlock', 'Wizard'],
    },
    {
        name: 'Seeming',
        level: 5,
        school: 'Illusion',
        castingTime: '1 action',
        range: '30 ft',
        components: 'V, S',
        description: 'This spell allows you to change the appearance of any number of creatures that you can see within range.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Teleportation Circle',
        level: 5,
        school: 'Conjuration',
        castingTime: '1 minute',
        range: '10 ft',
        components: 'V, S, M',
        description: 'You draw a 10-foot-diameter circle on the ground inscribed with sigils that link your location to a permanent teleportation circle.',
        requiresConcentration: false,
        classes: ['Bard', 'Sorcerer', 'Wizard'],
    },
    {
        name: 'Wall of Force',
        level: 5,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'An invisible wall of force springs into existence at a point you choose within range.',
        element: 'force',
        requiresConcentration: true,
        classes: ['Wizard'],
    },
    {
        name: 'Wall of Stone',
        level: 5,
        school: 'Evocation',
        castingTime: '1 action',
        range: '120 ft',
        components: 'V, S, M',
        description: 'A nonmagical wall of solid stone springs into existence at a point you choose within range.',
        requiresConcentration: true,
        classes: ['Druid', 'Sorcerer', 'Wizard', 'Artificer'],
    },
];